version: "3.9"
services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - prometheus_network


networks:
  prometheus_network:
    driver: bridge